run:
  timeout: 3m
  tests: true
  build-tags: []
  modules-download-mode: readonly

# issues:
#   exclude-use-default: false
#   exclude-dirs-use-default: false

linters:
  enable:
    - errcheck
    - govet
    - gofmt
    - gosimple
    - staticcheck
    - unused
    - typecheck
    - ineffassign

output:
  formats:
    - format: colored-line-number