log-level: trace
port: 8080

kubeconfig: "/home/codespace/.kube/config"

informer:
  enabled: true

clusters:
  - name: cluster-a
    kubeconfig: "/home/codespace/.kube/cluster-a.yaml"
    namespace: default
  - name: cluster-b
    kubeconfig: "/home/codespace/.kube/cluster-b.yaml"
    namespace: kube-system
