apiVersion: v1
kind: Service
metadata:
  name: k8s-controller
spec:
  type: ClusterIP
  selector:
    app: k8s-controller
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
