# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: k8s-controller
# spec:
#   template:
#     spec:
#       containers:
#         - name: controller
#           envFrom:
#             - configMapRef:
#                 name: controller-config
